---
language: ruby

bundler_args: --without system_tests development

cache: bundler

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
  - gem list

sudo: false

script: 'puppet help; SPEC_OPTS="--format documentation" bundle exec rake validate'

matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION=">= 3.8.5"

notifications:
  email: false